# Python CircleCI 2.0 configuration file
version: 2.1
executors: 
  default-executor:
    docker:
      - image: cimg/base:2023.01
    working_directory: /tmp

workflows:
  ci_build:
    jobs:
      - save_hello_world_output:
          name: Hello-Job
      - print_output_file:
          requires:
              - Hello-Job
      - build:
          name: Build-Job
          requires:
            - Hello-Job
jobs:
  save_hello_world_output:
    executor: default-executor
    steps:
      - run: mkdir -p workspace
      - run:
          name: Save Hello world to a a cache
          command: echo "Hello, World from Eric Kasakya" > workspace/output.txt
      - persist_to_workspace:
          root: workspace
          paths:
            - output.txt

  print_output_file:
    executor: default-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          if [[ `cat /tmp/workspace/output.txt` == "Hello, World from Eric Kasakya" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v --cov=calculator