# Python CircleCI 2.1 configuration file
version: 2.1
executors: 
  python-excutor:
    docker:
      - image: circleci/python:3.7
    working_directory: /tmp
workflows:
  ci_build:
    jobs:
      - build
      - test:
          requires:
            - build

jobs:
  build:
    executor: python-excutor
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            flake8 --exclude=venv* --statistics
      - persist_to_workspace:
          root: ~/
          paths:
            - venv/*
  test:
    executor: python-excutor
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
            pytest -v --cov=calculator